defmodule PhxCustom.MixProject do
  use Mix.Project

  @repo_url "https://github.com/c4710n/phx_custom"

  def project do
    [
      app: :phx_custom,
      version: "0.2.4",
      elixir: "~> 1.9",
      start_permanent: Mix.env() == :prod,
      deps: deps(),
      package: package(),
      description: description()
    ]
  end

  # Run "mix help compile.app" to learn about applications.
  def application do
    [
      extra_applications: [:logger]
    ]
  end

  # Run "mix help deps" to learn about dependencies.
  defp deps do
    [
      # {:dep_from_hexpm, "~> 0.3.0"},
      # {:dep_from_git, git: "https://github.com/elixir-lang/my_dep.git", tag: "0.1.0"}
    ]
  end

  defp description do
    "Custom official template generated by `mix phx.new` with my own needs."
  end

  defp package do
    [
      files: ~w(lib priv mix.exs .formatter.exs README*),
      exclude_patterns: [".DS_Store", "priv/example-projects"],
      licenses: ["MIT"],
      links: %{
        "GitHub" => @repo_url
      }
    ]
  end
end
